- hosts: VM
  tasks:
  - name: Start environment preparation for VM
    script: ./install_VM_packages.sh
  - name: Ð¡opy make_prediction.py
    copy:
      src: ./make_prediction.py
      dest: ~/
  - name: Start making prediction
    script: ./make_prediction.py
    args:
      executable: python3

